# Generated by Django 4.2.6 on 2023-11-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maindnadatabase',
            options={'ordering': ['id'], 'verbose_name': 'dnazyme', 'verbose_name_plural': 'dnazymes'},
        ),
        migrations.RemoveField(
            model_name='maindnadatabase',
            name='buffer',
        ),
        migrations.RemoveField(
            model_name='maindnadatabase',
            name='catalytic_core',
        ),
        migrations.RemoveField(
            model_name='maindnadatabase',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='maindnadatabase',
            name='kobs',
        ),
        migrations.RemoveField(
            model_name='maindnadatabase',
            name='metal_ions',
        ),
        migrations.RemoveField(
            model_name='maindnadatabase',
            name='name',
        ),
        migrations.AddField(
            model_name='maindnadatabase',
            name='activity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='maindnadatabase',
            name='sequence',
            field=models.CharField(default='', max_length=96),
        ),
        migrations.AddField(
            model_name='maindnadatabase',
            name='year_of_publication',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maindnadatabase',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='maindnadatabase',
            table='dnazyme',
        ),
    ]
