# Generated by Django 4.2.6 on 2023-10-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindatabase',
            name='core',
            field=models.CharField(default='', max_length=100, verbose_name='catalytic core'),
        ),
        migrations.AddField(
            model_name='maindatabase',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
        ),
    ]
