# Generated by Django 4.2.6 on 2023-12-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_maindnadatabase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindnadatabase',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
