# Generated by Django 4.2.6 on 2023-10-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_maindatabase_core_maindatabase_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maindatabase',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='maindatabase',
            table='main_db',
        ),
    ]
