# Generated by Django 4.2.6 on 2024-03-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_maindnadatabase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindnadatabase',
            name='buffer',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='maindnadatabase',
            name='doi',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='maindnadatabase',
            name='metal_ions',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='maindnadatabase',
            name='temperature',
            field=models.FloatField(default=25),
        ),
    ]
