# Generated by Django 4.2.6 on 2023-12-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_maindnadatabase_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sequence', models.CharField(default='', max_length=96)),
                ('activity', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'candidate',
                'verbose_name_plural': 'candidates',
                'db_table': 'candidates',
                'ordering': ['id'],
            },
        ),
    ]
