# Generated by Django 4.2.6 on 2024-03-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_maindnadatabase_buffer_maindnadatabase_doi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maindnadatabase',
            name='year_of_publication',
        ),
    ]
